# example config
- name: "kind/subtask"
  color: "C611F0"
  description: ""
- name: "do-not-merge/wip"
  color: "8F11FA"
  description: ""
- name: "documentation/content-needed"
  color: "501BE3"
  description: "content needed"
- name: "documentation/grammar-error"
  color: "1113FA"
  description: "grammar error"
- name: "kind/api-change"
  color: "114DF0"
  description: ""
- name: "kind/bug"
  color: "FA1139"
  description: ""
- name: "kind/design"
  color: "F09311"
  description: ""
- name: "kind/documentation"
  color: "A234E6"
  description: ""
- name: "kind/enhancement"
  color: "FCC9BD"
  description: ""
- name: "kind/feature"
  color: "F2D468"
  description: ""
- name: "kind/investigate"
  color: "D7F5DE"
  description: ""
- name: "kind/performance"
  color: "91BDFF"
  description: ""
- name: "kind/refactor"
  color: "E29FE6"
  description: ""
- name: "kind/task"
  color: "FCBF95"
  description: ""
- name: "MatrixCamp"
  color: "F2F1D8"
  description: ""
- name: "Moderate"
  color: "F6B3BA"
  description: ""
- name: "needs-triage"
  color: "CFC0B4"
  description: ""
- name: "triage/accepted"
  color: "E8E4CC"
  description: ""
- name: "priority/p0"
  color: "98FF66"
  description: ""
- name: "priority/p1"
  color: "A3F4DC"
  description: ""
- name: "priority/p2"
  color: "DFB5F7"
  description: ""
- name: "priority/p3"
  color: "CFBAB4"
  description: ""
- name: "release-notes"
  color: "E8E4CC"
  description: ""
- name: "severity/s0"
  color: "FF4D46"
  description: ""
- name: "severity/s1"
  color: "FF776F"
  description: ""
- name: "severity/s2"
  color: "FF564D"
  description: ""
- name: "severity/s3"
  color: "FF7F77"
  description: ""
- name: "size/xxl"
  color: "D7EDD5"
  description: ""
- name: "size/xl"
  color: "A674D6"
  description: ""
- name: "size/l"
  color: "FAE39B"
  description: ""
- name: "size/m"
  color: "78D1FF"
  description: ""
- name: "size/s"
  color: "64F074"
  description: ""
- name: "source/benchmark"
  color: "77CDFF"
  description: ""
- name: "source/on-demand"
  color: "65F075"
  description: ""
- name: "source/proposal"
  color: "90D90D"
  description: ""