version: 1

# The number of changed lines is calculated as the sum of all additions + deletions in the PR.
labels:
  - label: "size/s"
    size-below: 10
  - label: "siz/m"
    size-above: 9
    size-below: 100
  - label: "size/l"
    size-above: 100